apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d275yqtnj-python 
  janus-idp.io/tekton: d275yqtnj-python
  backstage.io/kubernetes-id: d275yqtnj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d275yqtnj-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml